### Import librairies

In [169]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn import metrics
from matplotlib import rcParams
rcParams['figure.figsize'] = 11.7,8.27

### Import dataset

In [170]:
df = pd.read_json(r"data_harvest_full.json", lines=True)
df.head()

,url,status,location,version,price,year,mileage,fuel_type,emission,fuel_usage,transmission,door_nb,technical_power,seat_nb,actual_power,body_colour,body_type
0,https://www.paruvendu.fr/a/voiture-occasion/da...,200,dissay (86130),version duster tce 130 fap 4x2 prestige,prix 17 600 €,année février 2019 le comparateur d'assurance ...,kilométrage 18 300 km,energie essence,N/A,N/A,transmission manuelle,nb de portes 4 portes avec hayon,puissance fiscale 7 cv,nombre de places 5 places,130,blanc,4x4
1,https://www.paruvendu.fr/a/voiture-occasion/mi...,200,59240 dunkerque,version cooper s red hot chili 192 cv bva,prix 24 990 €,année mai 2018 le comparateur d'assurance pour...,kilométrage 47 500 km,energie essence,emissions de co2 119 g/km,N/A,transmission automatique,nb de portes 2 portes avec hayon,puissance fiscale 10 cv,nombre de places 4 places,192,rouge foncé,berline
2,https://www.paruvendu.fr/a/voiture-occasion/ni...,200,53000 laval,version 1.5 dci 110ch fap ultimate edition,prix 8 490 €,année octobre 2013 le comparateur d'assurance ...,kilométrage 166 400 km,energie diesel,emissions de co2 129 g/km,N/A,transmission manuelle,nb de portes 4 portes avec hayon,puissance fiscale 6 cv,nombre de places 5 places,110,gris,break
3,https://www.paruvendu.fr/a/voiture-occasion/ni...,200,belley (01300),version qashqai 1.6 dci 130 xtronic tekna,prix 16 900 €,année octobre 2016 le comparateur d'assurance ...,kilométrage 61 500 km,energie diesel,emissions de co2 128 g/km,consommation mixte 4.9 litres / 100 km,transmission automatique,nb de portes 4 portes avec hayon,puissance fiscale 7 cv,nombre de places 5 places,130,gris foncé,4x4
4,https://www.paruvendu.fr/a/voiture-occasion/mi...,200,30200 bagnols-sur-cèze,version one d 95 ch edition blackfriars,prix 17 900 €,année février 2018 le comparateur d'assurance ...,kilométrage 58 529 km,energie diesel,emissions de co2 99 g/km,N/A,transmission manuelle,nb de portes 4 portes avec hayon,puissance fiscale 5 cv,nombre de places 5 places,95,gris,berline

In [171]:
df_clean=df.drop(['status'],axis=1)

In [172]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17231 entries, 0 to 17230
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   url              17231 non-null  object
 1   location         17231 non-null  object
 2   version          17231 non-null  object
 3   price            17231 non-null  object
 4   year             17231 non-null  object
 5   mileage          17231 non-null  object
 6   fuel_type        17231 non-null  object
 7   emission         17231 non-null  object
 8   fuel_usage       17231 non-null  object
 9   transmission     17231 non-null  object
 10  door_nb          17231 non-null  object
 11  technical_power  17231 non-null  object
 12  seat_nb          17231 non-null  object
 13  actual_power     17231 non-null  object
 14  body_colour      17231 non-null  object
 15  body_type        17231 non-null  object
dtypes: object(16)
memory usage: 2.1+ MB

In [173]:
for i in range(0, len(df_clean)): 
    df_clean.iloc[i].fuel_type = df_clean.iloc[i].fuel_type[8:] 

for i in range(0, len(df_clean)): 
    df_clean.iloc[i].emission = df_clean.iloc[i].emission[17:-5] 

for i in range(0, len(df_clean)): 
    df_clean.iloc[i].transmission = df_clean.iloc[i].transmission[13:] 

for i in range(0, len(df_clean)): 
    df_clean.iloc[i].fuel_usage = df_clean.iloc[i].fuel_usage[19:-16] 

for i in range(0, len(df_clean)): 
    df_clean.iloc[i].url = df_clean.iloc[i].url[44:] 

for i in range(0, len(df_clean)): 
    df_clean.iloc[i].version = df_clean.iloc[i].version[8:] 

for i in range(0, len(df_clean)): 
    df_clean.iloc[i].year = df_clean.iloc[i].year[:] 

df_clean['door_nb'] = df_clean['door_nb'].str.replace(r'\D', '')
df_clean['seat_nb'] = df_clean['seat_nb'].str.replace(r'\D', '')
df_clean['location'] = df_clean['location'].str.replace(r'\D', '')
df_clean['price'] = df_clean['price'].str.replace(r'\D', '')
df_clean['mileage'] = df_clean['mileage'].str.replace(r'\D', '')
df_clean['technical_power'] = df_clean['technical_power'].str.replace(r'\D', '')
df_clean.head()

C:\Users\utilisateur\AppData\Local\Temp\ipykernel_6260\738009291.py:22: FutureWarning: The default value of regex will change from True to False in a future version.
  df_clean['door_nb'] = df_clean['door_nb'].str.replace(r'\D', '')
C:\Users\utilisateur\AppData\Local\Temp\ipykernel_6260\738009291.py:23: FutureWarning: The default value of regex will change from True to False in a future version.
  df_clean['seat_nb'] = df_clean['seat_nb'].str.replace(r'\D', '')
C:\Users\utilisateur\AppData\Local\Temp\ipykernel_6260\738009291.py:24: FutureWarning: The default value of regex will change from True to False in a future version.
  df_clean['location'] = df_clean['location'].str.replace(r'\D', '')
C:\Users\utilisateur\AppData\Local\Temp\ipykernel_6260\738009291.py:25: FutureWarning: The default value of regex will change from True to False in a future version.
  df_clean['price'] = df_clean['price'].str.replace(r'\D', '')
C:\Users\utilisateur\AppData\Local\Temp\ipykernel_6260\738009291.py:26: FutureWarning: The default value of regex will change from True to False in a future version.
  df_clean['mileage'] = df_clean['mileage'].str.replace(r'\D', '')
C:\Users\utilisateur\AppData\Local\Temp\ipykernel_6260\738009291.py:27: FutureWarning: The default value of regex will change from True to False in a future version.
  df_clean['technical_power'] = df_clean['technical_power'].str.replace(r'\D', '')

,url,location,version,price,year,mileage,fuel_type,emission,fuel_usage,transmission,door_nb,technical_power,seat_nb,actual_power,body_colour,body_type
0,dacia/duster/1260688891A1KVVODCDUS,86130,duster tce 130 fap 4x2 prestige,17600,année février 2019 le comparateur d'assurance ...,18300,essence,,,manuelle,4,7,5,130,blanc,4x4
1,mini/cooper/1260799421A1KVVOMCCOO,59240,cooper s red hot chili 192 cv bva,24990,année mai 2018 le comparateur d'assurance pour...,47500,essence,119,,automatique,2,10,4,192,rouge foncé,berline
2,nissan/qashqai/1260796406A1KVVONIQAS,53000,1.5 dci 110ch fap ultimate edition,8490,année octobre 2013 le comparateur d'assurance ...,166400,diesel,129,,manuelle,4,6,5,110,gris,break
3,nissan/qashqai/1260447237A1KVVONIQAS,01300,qashqai 1.6 dci 130 xtronic tekna,16900,année octobre 2016 le comparateur d'assurance ...,61500,diesel,128,4.9,automatique,4,7,5,130,gris foncé,4x4
4,mini/cooper/1258307414A1KVVOMCCOO,30200,one d 95 ch edition blackfriars,17900,année février 2018 le comparateur d'assurance ...,58529,diesel,99,,manuelle,4,5,5,95,gris,berline

In [174]:
df_marque=df_clean['url'].str.split('/1',expand=True)
df_clean['marque']=df_marque[0]
df_clean.drop(columns =["url"], inplace = True)

df_marque=df_clean['marque'].str.split('/',expand=True)
df_clean['marque']=df_marque[0]
df_clean['modele']=df_marque[1]

df_year=df_clean['year'].str.split(' le',expand=True)
df_clean['date_fabrication']=df_year[0]
df_clean.drop(columns =["year"], inplace = True)

df_clean['date_fabrication'] = df_clean['date_fabrication'].str.replace(r'\D', '')

df_clean.head()

C:\Users\utilisateur\AppData\Local\Temp\ipykernel_6260\3552035871.py:13: FutureWarning: The default value of regex will change from True to False in a future version.
  df_clean['date_fabrication'] = df_clean['date_fabrication'].str.replace(r'\D', '')

,location,version,price,mileage,fuel_type,emission,fuel_usage,transmission,door_nb,technical_power,seat_nb,actual_power,body_colour,body_type,marque,modele,date_fabrication
0,86130,duster tce 130 fap 4x2 prestige,17600,18300,essence,,,manuelle,4,7,5,130,blanc,4x4,dacia,duster,2019
1,59240,cooper s red hot chili 192 cv bva,24990,47500,essence,119,,automatique,2,10,4,192,rouge foncé,berline,mini,cooper,2018
2,53000,1.5 dci 110ch fap ultimate edition,8490,166400,diesel,129,,manuelle,4,6,5,110,gris,break,nissan,qashqai,2013
3,01300,qashqai 1.6 dci 130 xtronic tekna,16900,61500,diesel,128,4.9,automatique,4,7,5,130,gris foncé,4x4,nissan,qashqai,2016
4,30200,one d 95 ch edition blackfriars,17900,58529,diesel,99,,manuelle,4,5,5,95,gris,berline,mini,cooper,2018

In [175]:
df_clean['actual_power']=df_clean['actual_power'].replace('N/A', 0)
df_clean=df_clean.replace('N/A', np.nan)
df_clean=df_clean.replace('', 0)
df_clean['emission']=df_clean['emission'].replace('nc', 0)
df_clean.head()

,location,version,price,mileage,fuel_type,emission,fuel_usage,transmission,door_nb,technical_power,seat_nb,actual_power,body_colour,body_type,marque,modele,date_fabrication
0,86130,duster tce 130 fap 4x2 prestige,17600,18300,essence,0,0,manuelle,4,7,5,130,blanc,4x4,dacia,duster,2019
1,59240,cooper s red hot chili 192 cv bva,24990,47500,essence,119,0,automatique,2,10,4,192,rouge foncé,berline,mini,cooper,2018
2,53000,1.5 dci 110ch fap ultimate edition,8490,166400,diesel,129,0,manuelle,4,6,5,110,gris,break,nissan,qashqai,2013
3,01300,qashqai 1.6 dci 130 xtronic tekna,16900,61500,diesel,128,4.9,automatique,4,7,5,130,gris foncé,4x4,nissan,qashqai,2016
4,30200,one d 95 ch edition blackfriars,17900,58529,diesel,99,0,manuelle,4,5,5,95,gris,berline,mini,cooper,2018

In [176]:
df_clean=df_clean.rename(columns={"location": "code_postal", "price": "prix_vente", "mileage": "kilometrage",
 "fuel_type": "energie", "fuel_usage": "consommation", "door_nb": "portes",
  "technical_power": "cv_fiscaux", "actual_power": "cv_reels", "body_colour": "couleur", "body_type": "carrosserie", "seat_nb": "sieges"})
df_clean.head()

,code_postal,version,prix_vente,kilometrage,energie,emission,consommation,transmission,portes,cv_fiscaux,sieges,cv_reels,couleur,carrosserie,marque,modele,date_fabrication
0,86130,duster tce 130 fap 4x2 prestige,17600,18300,essence,0,0,manuelle,4,7,5,130,blanc,4x4,dacia,duster,2019
1,59240,cooper s red hot chili 192 cv bva,24990,47500,essence,119,0,automatique,2,10,4,192,rouge foncé,berline,mini,cooper,2018
2,53000,1.5 dci 110ch fap ultimate edition,8490,166400,diesel,129,0,manuelle,4,6,5,110,gris,break,nissan,qashqai,2013
3,01300,qashqai 1.6 dci 130 xtronic tekna,16900,61500,diesel,128,4.9,automatique,4,7,5,130,gris foncé,4x4,nissan,qashqai,2016
4,30200,one d 95 ch edition blackfriars,17900,58529,diesel,99,0,manuelle,4,5,5,95,gris,berline,mini,cooper,2018

In [177]:
df_clean.dtypes

code_postal         object
version             object
prix_vente          object
kilometrage         object
energie             object
emission            object
consommation        object
transmission        object
portes              object
cv_fiscaux          object
sieges              object
cv_reels            object
couleur             object
carrosserie         object
marque              object
modele              object
date_fabrication    object
dtype: object

In [178]:
df_clean['emission']=df_clean['emission'].astype(float)
df_clean['consommation']=df_clean['consommation'].astype(float)
df_clean=df_clean.astype({'emission': 'int','kilometrage': 'int','prix_vente': 'int','code_postal': 'int','portes': 'int', 'cv_fiscaux': 'int', 'cv_reels': 'int', 'date_fabrication': 'int', 'sieges': 'int'})
df_clean.dtypes

code_postal           int32
version              object
prix_vente            int32
kilometrage           int32
energie              object
emission              int32
consommation        float64
transmission         object
portes                int32
cv_fiscaux            int32
sieges                int32
cv_reels              int32
couleur              object
carrosserie          object
marque               object
modele               object
date_fabrication      int32
dtype: object

In [179]:
df_clean = df_clean[['version','marque','modele','date_fabrication','kilometrage','couleur','carrosserie'
,'code_postal','energie','emission','consommation','transmission','portes','sieges','cv_fiscaux','cv_reels','prix_vente']]
df_clean.head(10)

,version,marque,modele,date_fabrication,kilometrage,couleur,carrosserie,code_postal,energie,emission,consommation,transmission,portes,sieges,cv_fiscaux,cv_reels,prix_vente
0,duster tce 130 fap 4x2 prestige,dacia,duster,2019,18300,blanc,4x4,86130,essence,0,0.0,manuelle,4,5,7,130,17600
1,cooper s red hot chili 192 cv bva,mini,cooper,2018,47500,rouge foncé,berline,59240,essence,119,0.0,automatique,2,4,10,192,24990
2,1.5 dci 110ch fap ultimate edition,nissan,qashqai,2013,166400,gris,break,53000,diesel,129,0.0,manuelle,4,5,6,110,8490
3,qashqai 1.6 dci 130 xtronic tekna,nissan,qashqai,2016,61500,gris foncé,4x4,1300,diesel,128,4.9,automatique,4,5,7,130,16900
4,one d 95 ch edition blackfriars,mini,cooper,2018,58529,gris,berline,30200,diesel,99,0.0,manuelle,4,5,5,95,17900
5,mini cooper 136 ch edition blackfriars,mini,cooper,2017,58000,NaN,berline,70300,essence,107,4.6,manuelle,2,4,7,136,17800
6,mini cabriolet 231 ch john cooper works bva8,mini,cooper,2018,41500,bleu clair,cabriolet,67120,essence,136,5.9,automatique,2,4,14,0,31900
7,duster dci 110 edc 4x2 confort,dacia,duster,2018,36500,blanc,4x4,18130,diesel,116,4.5,automatique,4,5,6,110,15400
8,ii 1.2 8v s&s pop,fiat,500,2010,105733,blanc,berline,31390,essence,0,0.0,manuelle,2,4,4,0,6900
9,duster 1.5 dci 110 4x2 ambiance,dacia,duster,2012,124111,gris clair,4x4,20137,diesel,130,5.0,manuelle,4,5,6,107,8000

In [180]:
df_clean['version'].value_counts()

0                                                       1542
420i 184 bva8 m sport +toit ouvrant cuir surequipã©e      36
bluehdi 130 eat8 rivoli                                   36
136h technoline                                           35
1.5 dci 110 bvm6 n-connecta                               35
                                                        ...
3.8 turbo pdk cabriolet                                    1
3.8 carrera 4s pdk                                         1
1.5 blue dci 95ch business gps radar ar                    1
captur dci 90 edc intens                                   1
206 2.0 hdi xt premium                                     1
Name: version, Length: 9486, dtype: int64

In [181]:
df_clean.shape

(17231, 17)

In [182]:
def getActualPowerFromVersion(version : str):
    cleanActualPower = ''
    for char in version:
        if char in ('0','1','2','3','4','5','6','7','8','9',' ','.', 'x'):
            cleanActualPower += char
    cleanActualPowerArr = cleanActualPower.split(' ')
    biggestNum = 0
    for numero in cleanActualPowerArr:
        if numero.isdecimal():
            if int(numero) not in (500, 205, 206, 207, 208):
                if int(numero)>40 and int(numero)<500:
                    if int(numero) > biggestNum:
                        biggestNum = int(numero)
    if biggestNum == 0:
        return np.nan
    else:
        return str(biggestNum)

df_clean['cvfromversion'] = df_clean['version'].apply(lambda x : getActualPowerFromVersion(str(x)))

In [183]:
# # df_clean['cvfromversion'].compare(df_clean['cv_reels'],keep_equal=True)
# for i in range(0, len(df_clean)): 
#     if df_clean.iloc[i].cv_reels==0:
#         if df_clean.iloc[i].cvfromversion!="NaN":
#             df_clean.iloc[i].cv_reels=df_clean.iloc[i].cvfromversion
df_clean['cvfromversion']=df_clean['cvfromversion'].fillna(0)
df_clean.loc[df_clean.cv_reels == 0, 'cv_reels'] = df_clean.cvfromversion

In [184]:
df_clean=df_clean.drop(['version','cvfromversion'],axis=1)

In [185]:
df_clean.head(10)

,marque,modele,date_fabrication,kilometrage,couleur,carrosserie,code_postal,energie,emission,consommation,transmission,portes,sieges,cv_fiscaux,cv_reels,prix_vente
0,dacia,duster,2019,18300,blanc,4x4,86130,essence,0,0.0,manuelle,4,5,7,130,17600
1,mini,cooper,2018,47500,rouge foncé,berline,59240,essence,119,0.0,automatique,2,4,10,192,24990
2,nissan,qashqai,2013,166400,gris,break,53000,diesel,129,0.0,manuelle,4,5,6,110,8490
3,nissan,qashqai,2016,61500,gris foncé,4x4,1300,diesel,128,4.9,automatique,4,5,7,130,16900
4,mini,cooper,2018,58529,gris,berline,30200,diesel,99,0.0,manuelle,4,5,5,95,17900
5,mini,cooper,2017,58000,NaN,berline,70300,essence,107,4.6,manuelle,2,4,7,136,17800
6,mini,cooper,2018,41500,bleu clair,cabriolet,67120,essence,136,5.9,automatique,2,4,14,231,31900
7,dacia,duster,2018,36500,blanc,4x4,18130,diesel,116,4.5,automatique,4,5,6,110,15400
8,fiat,500,2010,105733,blanc,berline,31390,essence,0,0.0,manuelle,2,4,4,0,6900
9,dacia,duster,2012,124111,gris clair,4x4,20137,diesel,130,5.0,manuelle,4,5,6,107,8000

In [186]:
df_clean.to_json(r'data_harvest_clean.json',orient='records')